A raw descriptor creation interface for the unvault
re-vault/revault pull request #17
Opened 2020-09-26 00:29 UTC by darosior

This is based on #10 (itself base on #15 ...), see: 
- cd829a3
- 5feaa58 

This adds an interface to fix #14 .
Good news: we can apparently support threshold-based managers set.
Question news: what now ?

2020-09-26 12:13 UTC, JSwambo commented
Ack 5feaa58fde48cb0d960778d3885fed82a42bca5f

2020-09-26 13:34 UTC, darosior commented
Rebased after #10 rebase.

2020-09-28 09:16 UTC, edouardparis requested changes
small error s/`bitcoinconsensus`/`bitcoin::consensus`
clippy found it

2020-09-28 13:17 UTC, darosior commented
Thanks!

2020-09-28 13:22 UTC, darosior commented
Actually it's that i (apparently) did not move it as part of the test mod.
And fwiw: bitcoin::consensus != libbitcoinconsensus.

2020-09-28 13:28 UTC, darosior commented
Ok I actually fucked up the rebase, should be fixed now.

2020-10-02 09:03 UTC, darosior commented
Rebased after #10 rebase.

2020-10-02 09:43 UTC, darosior commented
Rebased on master after #10 merge.

2020-10-02 10:29 UTC, JSwambo approved these changes
Ack 2855c5b9ef1423a11b84aaca24921cf0a4608db8

2020-10-02 12:38 UTC, merged